"""TikTok coverage baseline and deliberate follow-up inventory."""

PROVIDER_METADATA = {
    "provider": "tiktok",
    "api_version": "v1.3",
    "source_url": "https://business-api.tiktok.com/portal/docs",
    "inventory_scope": "official_open_api_baseline",
    "completeness": "scoped_not_exhaustive",
}

OFFICIAL_INVENTORY = [
    {"resource": "advertiser", "action": "list", "status": "implemented", "surface_method": "list_accounts", "provider_operation": "advertiser/info"},
    {"resource": "campaign", "action": "crud", "status": "implemented", "surface_method": "create_campaign", "provider_operation": "campaign/create|update|delete|get"},
    {"resource": "ad_group", "action": "crud", "status": "implemented", "surface_method": "create_adgroup", "provider_operation": "adgroup/create|update|delete|get"},
    {"resource": "ad", "action": "crud", "status": "implemented", "surface_method": "create_ad", "provider_operation": "ad/create|update|delete|get"},
    {"resource": "audience", "action": "crud", "status": "implemented", "surface_method": "create_audience", "provider_operation": "audience/*"},
    {"resource": "targeting_reference", "action": "read", "status": "implemented", "surface_method": "list_locations", "provider_operation": "tool/* reference endpoints"},
    {"resource": "pixel", "action": "crud", "status": "implemented", "surface_method": "create_pixel", "provider_operation": "pixel/*"},
    {"resource": "pixel_event", "action": "send", "status": "implemented", "surface_method": "send_pixel_event", "provider_operation": "pixel/track"},
    {"resource": "report", "action": "read", "status": "implemented", "surface_method": "get_report", "provider_operation": "report/integrated/get"},
    {"resource": "asset_library", "action": "crud", "status": "implemented", "surface_method": "upload_image", "provider_operation": "file/image/ad/upload|file/video/ad/upload"},
    {"resource": "app", "action": "list", "status": "implemented", "surface_method": "list_apps", "provider_operation": "app/list"},
    {"resource": "catalog", "action": "read", "status": "implemented", "surface_method": "list_catalogs", "provider_operation": "catalog/list"},
    {"resource": "creative", "action": "crud", "status": "planned", "provider_operation": "creative management endpoints"},
    {"resource": "automated_rule", "action": "crud", "status": "planned", "provider_operation": "automated_rule/*"},
    {"resource": "comment", "action": "crud", "status": "planned", "provider_operation": "comment/*"},
    {"resource": "catalog", "action": "crud", "status": "planned", "provider_operation": "catalog/* create|update|delete"},
    {"resource": "product_set", "action": "crud", "status": "planned", "provider_operation": "product_set/* create|update|delete"},
]

API_SURFACE = [
    {"resource": "account", "action": "list", "method": "list_accounts", "status": "implemented"},
    {"resource": "campaign", "action": "crud", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "pause", "method": "pause_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "resume", "method": "resume_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "ad_group", "action": "crud", "method": "create_adgroup", "status": "implemented"},
    {"resource": "ad_group", "action": "create_product_sales", "method": "create_product_sales_adgroup", "status": "implemented"},
    {"resource": "ad_group", "action": "list", "method": "list_adgroups", "status": "implemented"},
    {"resource": "ad_group", "action": "get", "method": "get_adgroup", "status": "implemented"},
    {"resource": "ad_group", "action": "update", "method": "update_adgroup", "status": "implemented"},
    {"resource": "ad_group", "action": "pause", "method": "pause_adgroup", "status": "implemented"},
    {"resource": "ad", "action": "crud", "method": "create_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_product_sales", "method": "create_product_sales_ad", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "update", "method": "update_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_single_video", "method": "create_single_video_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_single_image", "method": "create_single_image_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_carousel", "method": "create_carousel_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_lead", "method": "create_lead_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_app", "method": "create_app_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_spark", "method": "create_spark_ad", "status": "implemented"},
    {"resource": "audience", "action": "list", "method": "list_audiences", "status": "implemented"},
    {"resource": "audience", "action": "get", "method": "get_audience", "status": "implemented"},
    {"resource": "audience", "action": "create_customer_file", "method": "create_audience", "status": "implemented"},
    {"resource": "interest_category", "action": "list", "method": "list_interest_categories", "status": "implemented"},
    {"resource": "interest_category", "action": "get", "method": "get_interest_category", "status": "implemented"},
    {"resource": "action_category", "action": "list", "method": "list_action_categories", "status": "implemented"},
    {"resource": "language", "action": "list", "method": "list_languages", "status": "implemented"},
    {"resource": "browser", "action": "list", "method": "list_browsers", "status": "implemented"},
    {"resource": "carrier", "action": "list", "method": "list_carriers", "status": "implemented"},
    {"resource": "device", "action": "list", "method": "list_devices", "status": "implemented"},
    {"resource": "operating_system", "action": "list", "method": "list_operating_systems", "status": "implemented"},
    {"resource": "device_model", "action": "list", "method": "list_device_models", "status": "implemented"},
    {"resource": "interest_keyword", "action": "recommend", "method": "recommend_interest_keywords", "status": "implemented"},
    {"resource": "location", "action": "list", "method": "list_locations", "status": "implemented"},
    {"resource": "location", "action": "search", "method": "search_locations", "status": "implemented"},
    {"resource": "region", "action": "list", "method": "list_regions", "status": "implemented"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "creative_portfolio", "action": "create", "method": "create_creative_portfolio", "status": "implemented"},
    {"resource": "creative_portfolio", "action": "get", "method": "get_creative_portfolio", "status": "implemented"},
    {"resource": "creative_portfolio", "action": "preview", "method": "preview_creative_portfolio", "status": "implemented"},
    {"resource": "identity", "action": "create", "method": "create_identity", "status": "implemented"},
    {"resource": "identity", "action": "list", "method": "list_identities", "status": "implemented"},
    {"resource": "identity_video", "action": "get", "method": "get_identity_video_info", "status": "implemented"},
    {"resource": "video", "action": "list", "method": "list_videos", "status": "implemented"},
    {"resource": "image", "action": "list", "method": "list_images", "status": "implemented"},
    {"resource": "video", "action": "upload", "method": "upload_video", "status": "implemented"},
    {"resource": "image", "action": "upload", "method": "upload_image", "status": "implemented"},
    {"resource": "conversion", "action": "list", "method": "list_conversions", "status": "implemented"},
    {"resource": "conversion", "action": "get", "method": "get_conversion", "status": "implemented"},
    {"resource": "pixel", "action": "list", "method": "list_pixels", "status": "implemented"},
    {"resource": "pixel", "action": "get", "method": "get_pixel", "status": "implemented"},
    {"resource": "pixel", "action": "create", "method": "create_pixel", "status": "implemented"},
    {"resource": "pixel", "action": "update", "method": "update_pixel", "status": "implemented"},
    {"resource": "pixel", "action": "delete", "status": "planned", "gap": "TikTok Pixel 删除 endpoint 尚未完成版本化验证，暂不伪造删除 Tool"},
    {"resource": "pixel_event", "action": "send", "method": "send_pixel_event", "status": "implemented"},
    {"resource": "pixel_event_batch", "action": "send", "method": "send_pixel_events", "status": "implemented"},
    {"resource": "catalog", "action": "list", "method": "list_catalogs", "status": "implemented"},
    {"resource": "product_set", "action": "list", "method": "list_product_sets", "status": "implemented"},
    {"resource": "product_selection", "action": "validate", "method": "validate_product_selection", "status": "implemented"},
    {"resource": "app", "action": "list", "method": "list_apps", "status": "implemented"},
    {"resource": "report", "action": "get", "method": "get_report", "status": "implemented"},
    {"resource": "audience", "action": "delete", "method": "delete_audience", "status": "implemented"},
    {"resource": "audience", "action": "update", "method": "update_audience", "status": "implemented"},
    {"resource": "audience", "action": "source_upload", "method": "upload_audience_file", "status": "implemented"},
    {"resource": "creative", "action": "crud", "status": "planned", "gap": "TikTok 创意对象由广告创建接口生成，尚缺独立创意管理/编辑能力"},
    {"resource": "lead_form", "action": "crud", "status": "not_applicable", "gap": "Instant Form/Page 由 TikTok Instant Page Editor SDK 管理，不属于当前 Ads API CRUD；广告创建通过 page_id 引用"},
    {"resource": "catalog", "action": "crud", "status": "planned", "gap": "当前已提供 catalog/get、product_set/get 与 Product Selection 引用校验；Catalog/Product Set 创建、更新、删除尚无经过验证的 TikTok Ads API endpoint/Tool，不能伪造为已实现"},
    {"resource": "ad_group_targeting", "action": "update", "method": "update_adgroup_targeting", "status": "implemented"},
    {"resource": "brand_safety", "action": "list", "method": "list_brand_safety", "status": "implemented"},
    {"resource": "ad_group", "action": "report", "method": "get_adgroup_report", "status": "implemented"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
]
