"""TikTok coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "account", "action": "list", "method": "list_accounts", "status": "implemented"},
    {"resource": "campaign", "action": "crud", "method": "create_campaign", "status": "implemented"},
    {"resource": "ad_group", "action": "crud", "method": "create_adgroup", "status": "implemented"},
    {"resource": "ad", "action": "crud", "method": "create_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_lead", "method": "create_lead_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_app", "method": "create_app_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_spark", "method": "create_spark_ad", "status": "implemented"},
    {"resource": "audience", "action": "list", "method": "list_audiences", "status": "implemented"},
    {"resource": "audience", "action": "get", "method": "get_audience", "status": "implemented"},
    {"resource": "audience", "action": "create", "method": "create_audience", "status": "implemented"},
    {"resource": "interest_category", "action": "list", "method": "list_interest_categories", "status": "implemented"},
    {"resource": "location", "action": "list", "method": "list_locations", "status": "implemented"},
    {"resource": "location", "action": "search", "method": "search_locations", "status": "implemented"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "video", "action": "list", "method": "list_videos", "status": "implemented"},
    {"resource": "image", "action": "list", "method": "list_images", "status": "implemented"},
    {"resource": "conversion", "action": "list", "method": "list_conversions", "status": "implemented"},
    {"resource": "conversion", "action": "get", "method": "get_conversion", "status": "implemented"},
    {"resource": "catalog", "action": "list", "method": "list_catalogs", "status": "implemented"},
    {"resource": "product_set", "action": "list", "method": "list_product_sets", "status": "implemented"},
    {"resource": "app", "action": "list", "method": "list_apps", "status": "implemented"},
    {"resource": "report", "action": "get", "method": "get_report", "status": "implemented"},
    {"resource": "audience", "action": "delete", "method": "delete_audience", "status": "implemented"},
    {"resource": "audience", "action": "update", "status": "planned", "gap": "受众更新接口尚未完成验证"},
    {"resource": "audience", "action": "source_upload", "status": "planned", "gap": "受众来源上传尚无完整字段校验"},
    {"resource": "creative", "action": "crud", "status": "planned", "gap": "素材目前只有查询，缺少视频/图片上传和创意管理"},
    {"resource": "lead_form", "action": "crud", "status": "planned", "gap": "Lead Form 查询与创建尚无 Tool"},
    {"resource": "pixel", "action": "crud", "status": "planned", "gap": "Pixel/事件配置尚无 Tool"},
    {"resource": "catalog", "action": "crud", "status": "planned", "gap": "Catalog/Product Set 管理尚无完整 Tool"},
    {"resource": "ad_group_targeting", "action": "update", "status": "planned", "gap": "定向目前混在 Ad Group payload，缺少独立校验/枚举闭环"},
]
