"""Google Ads coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "pause", "method": "pause_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "resume", "method": "resume_campaign", "status": "implemented"},
    {"resource": "ad_group", "action": "list", "method": "list_ad_groups", "status": "implemented"},
    {"resource": "ad_group", "action": "get", "method": "get_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "create", "method": "create_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "update", "method": "update_ad_group", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "keyword", "action": "list", "method": "list_keywords", "status": "implemented"},
    {"resource": "keyword", "action": "create", "method": "create_keywords", "status": "implemented"},
    {"resource": "asset_group", "action": "list", "method": "list_asset_groups", "status": "implemented"},
    {"resource": "asset_group", "action": "get", "method": "get_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "create", "method": "create_pmax_asset_group", "status": "implemented"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_group", "action": "report", "method": "get_adgroup_report", "status": "implemented"},
    {"resource": "campaign_budget", "action": "list", "method": "list_campaign_budgets", "status": "implemented"},
    {"resource": "campaign_budget", "action": "get", "method": "get_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "create", "method": "create_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "update", "method": "update_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "delete", "method": "delete_campaign_budget", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "crud", "status": "planned", "gap": "出价策略资源尚无独立查询/管理 Tool"},
    {"resource": "campaign_criterion", "action": "crud", "status": "planned", "gap": "地域、受众和排除条件尚无独立 Criterion Tool"},
    {"resource": "conversion_action", "action": "crud", "status": "planned", "gap": "转化动作尚无查询/管理 Tool"},
    {"resource": "asset", "action": "crud", "status": "planned", "gap": "素材资源和素材关联尚无完整 Tool"},
    {"resource": "user_list", "action": "crud", "status": "planned", "gap": "第一方受众列表尚无独立 Tool"},
    {"resource": "customer_client", "action": "list", "status": "planned", "gap": "经理账户下客户枚举尚无 Tool"},
]
