"""Google Ads coverage baseline and deliberate follow-up inventory."""

PROVIDER_METADATA = {
    "provider": "google-ads",
    "api_version": "v24",
    "source_url": "https://developers.google.com/google-ads/api/reference/rpc/v24/overview",
    "inventory_scope": "official_resource_operations_baseline",
    "completeness": "scoped_not_exhaustive",
}

# This is intentionally a provider-owned, reviewable baseline rather than a
# claim that these are every Google Ads API method.  New resources/operations
# must be added here before they can be called "covered" in release reports.
OFFICIAL_INVENTORY = [
    {"resource": "campaign", "action": "list", "status": "implemented", "surface_method": "list_campaigns", "provider_operation": "GoogleAdsService.search: campaign"},
    {"resource": "campaign", "action": "mutate", "status": "implemented", "surface_method": "create_campaign", "provider_operation": "CampaignService.mutateCampaigns"},
    {"resource": "ad_group", "action": "list", "status": "implemented", "surface_method": "list_ad_groups", "provider_operation": "GoogleAdsService.search: ad_group"},
    {"resource": "ad_group", "action": "mutate", "status": "implemented", "surface_method": "create_ad_group", "provider_operation": "AdGroupService.mutateAdGroups"},
    {"resource": "ad", "action": "list", "status": "implemented", "surface_method": "list_ads", "provider_operation": "GoogleAdsService.search: ad_group_ad"},
    {"resource": "ad", "action": "mutate", "status": "implemented", "surface_method": "create_search_ad", "provider_operation": "AdGroupAdService.mutateAdGroupAds"},
    {"resource": "keyword", "action": "list", "status": "implemented", "surface_method": "list_keywords", "provider_operation": "GoogleAdsService.search: ad_group_criterion"},
    {"resource": "keyword", "action": "mutate", "status": "implemented", "surface_method": "create_keywords", "provider_operation": "AdGroupCriterionService.mutateAdGroupCriteria"},
    {"resource": "asset", "action": "list", "status": "implemented", "surface_method": "list_assets", "provider_operation": "GoogleAdsService.search: asset"},
    {"resource": "asset", "action": "mutate", "status": "implemented", "surface_method": "create_asset", "provider_operation": "AssetService.mutateAssets"},
    {"resource": "campaign_budget", "action": "mutate", "status": "implemented", "surface_method": "create_campaign_budget", "provider_operation": "CampaignBudgetService.mutateCampaignBudgets"},
    {"resource": "campaign_criterion", "action": "mutate", "status": "implemented", "surface_method": "create_campaign_criteria", "provider_operation": "CampaignCriterionService.mutateCampaignCriteria"},
    {"resource": "conversion_action", "action": "mutate", "status": "implemented", "surface_method": "create_conversion_action", "provider_operation": "ConversionActionService.mutateConversionActions"},
    {"resource": "user_list", "action": "mutate", "status": "implemented", "surface_method": "create_user_list", "provider_operation": "UserListService.mutateUserLists"},
    {"resource": "bidding_strategy", "action": "mutate", "status": "implemented", "surface_method": "create_bidding_strategy", "provider_operation": "BiddingStrategyService.mutateBiddingStrategies"},
    {"resource": "report", "action": "query", "status": "implemented", "surface_method": "get_campaign_report", "provider_operation": "GoogleAdsService.search/searchStream"},
    {"resource": "experiment", "action": "crud", "status": "planned", "provider_operation": "ExperimentService"},
    {"resource": "feed", "action": "crud", "status": "planned", "provider_operation": "FeedService / FeedItemService"},
    {"resource": "campaign_asset", "action": "mutate", "status": "implemented", "surface_method": "create_campaign_asset", "provider_operation": "CampaignAssetService.mutateCampaignAssets"},
    {"resource": "asset_group_asset", "action": "mutate", "status": "implemented", "surface_method": "create_asset_group_asset", "provider_operation": "AssetGroupAssetService.mutateAssetGroupAssets"},
    {"resource": "conversion_goal", "action": "mutate", "status": "planned", "provider_operation": "CustomerConversionGoalService / CampaignConversionGoalService"},
]

API_SURFACE = [
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "pause", "method": "pause_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "resume", "method": "resume_campaign", "status": "implemented"},
    {"resource": "ad_group", "action": "list", "method": "list_ad_groups", "status": "implemented"},
    {"resource": "ad_group", "action": "get", "method": "get_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "create", "method": "create_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "update", "method": "update_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "delete", "method": "delete_ad_group", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "delete", "method": "delete_ad", "status": "implemented"},
    {"resource": "ad", "action": "update", "method": "update_ad", "status": "implemented"},
    {"resource": "keyword", "action": "list", "method": "list_keywords", "status": "implemented"},
    {"resource": "keyword", "action": "create", "method": "create_keywords", "status": "implemented"},
    {"resource": "keyword", "action": "update", "method": "update_keyword", "status": "implemented"},
    {"resource": "keyword", "action": "delete", "method": "delete_keyword", "status": "implemented"},
    {"resource": "asset_group", "action": "list", "method": "list_asset_groups", "status": "implemented"},
    {"resource": "asset_group", "action": "get", "method": "get_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "create", "method": "create_pmax_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "update", "method": "update_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "live_create", "status": "planned", "gap": "PMax Asset Group live 多步 AssetService mutate 尚未经过指定测试账户验证"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_group", "action": "report", "method": "get_adgroup_report", "status": "implemented"},
    {"resource": "campaign_budget", "action": "list", "method": "list_campaign_budgets", "status": "implemented"},
    {"resource": "campaign_budget", "action": "get", "method": "get_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "create", "method": "create_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "update", "method": "update_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "delete", "method": "delete_campaign_budget", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "list", "method": "list_bidding_strategies", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "get", "method": "get_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "create", "method": "create_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "update", "method": "update_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "delete", "method": "delete_bidding_strategy", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "list", "method": "list_campaign_criteria", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "get", "method": "get_campaign_criterion", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "create", "method": "create_campaign_criteria", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "update", "method": "update_campaign_criterion", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "delete", "method": "delete_campaign_criterion", "status": "implemented"},
    {"resource": "conversion_action", "action": "list", "method": "list_conversion_actions", "status": "implemented"},
    {"resource": "conversion_action", "action": "get", "method": "get_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "create", "method": "create_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "update", "method": "update_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "delete", "method": "delete_conversion_action", "status": "implemented"},
    {"resource": "asset", "action": "list", "method": "list_assets", "status": "implemented"},
    {"resource": "asset", "action": "get", "method": "get_asset", "status": "implemented"},
    {"resource": "asset", "action": "create", "method": "create_asset", "status": "implemented"},
    {"resource": "asset", "action": "update", "status": "planned", "gap": "Google Asset 大多数字段不可变，更新语义尚未完成验证"},
    {"resource": "asset", "action": "delete", "method": "delete_asset", "status": "implemented", "notes": "AssetService remove；仍被引用的 Asset 由 Provider 拒绝"},
    {"resource": "campaign_asset", "action": "list", "method": "list_campaign_assets", "status": "implemented"},
    {"resource": "campaign_asset", "action": "create", "method": "create_campaign_asset", "status": "implemented"},
    {"resource": "campaign_asset", "action": "delete", "method": "delete_campaign_asset", "status": "implemented"},
    {"resource": "asset_group_asset", "action": "list", "method": "list_asset_group_assets", "status": "implemented"},
    {"resource": "asset_group_asset", "action": "create", "method": "create_asset_group_asset", "status": "implemented"},
    {"resource": "asset_group_asset", "action": "delete", "method": "delete_asset_group_asset", "status": "implemented"},
    {"resource": "product_group", "action": "create", "method": "create_product_group", "status": "implemented"},
    {"resource": "product_group", "action": "list", "method": "list_product_groups", "status": "implemented"},
    {"resource": "product_group", "action": "get", "method": "get_product_group", "status": "implemented"},
    {"resource": "product_group", "action": "update", "method": "update_product_group", "status": "implemented"},
    {"resource": "product_group", "action": "delete", "method": "delete_product_group", "status": "implemented"},
    {"resource": "ad", "action": "create_responsive_display", "method": "create_responsive_display_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_search", "method": "create_search_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_video", "method": "create_video_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_app", "method": "create_app_ad", "status": "implemented", "notes": "Dry-run AppAd payload builder; live mutation remains disabled until test-account verification"},
    {"resource": "ad_group", "action": "create_specialized", "method": "create_ad_group", "status": "implemented", "notes": "Specialized channel routing reuses the standard AdGroup resource"},
    {"resource": "ad", "action": "create_demand_gen_multi_asset", "method": "create_demand_gen_multi_asset_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_demand_gen_carousel", "method": "create_demand_gen_carousel_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_demand_gen_video_responsive", "method": "create_demand_gen_video_responsive_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_demand_gen_product", "method": "create_demand_gen_product_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_hotel", "method": "create_hotel_ad", "status": "implemented", "notes": "v24 feed-backed empty HotelAdInfo dry-run payload"},
    {"resource": "ad", "action": "create_local", "method": "create_local_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_smart_campaign", "method": "create_smart_campaign_ad", "status": "implemented", "notes": "v24 dry-run AdGroupAd payload builder"},
    {"resource": "ad", "action": "create_travel", "method": "create_travel_ad", "status": "implemented", "notes": "v24 feed-backed empty TravelAdInfo dry-run payload"},
    {"resource": "user_list", "action": "list", "method": "list_user_lists", "status": "implemented"},
    {"resource": "user_list", "action": "get", "method": "get_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "create", "method": "create_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "update", "method": "update_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "delete", "method": "delete_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "upload", "method": "upload_user_list_data", "status": "implemented"},
    {"resource": "customer_client", "action": "list", "method": "list_customer_clients", "status": "implemented"},
    {"resource": "experiment", "action": "list", "method": "list_experiments", "status": "implemented", "notes": "GAQL read surface; Experiment mutation lifecycle remains planned"},
    {"resource": "experiment_arm", "action": "list", "method": "list_experiment_arms", "status": "implemented", "notes": "GAQL read surface; Experiment Arm mutation lifecycle remains planned"},
]
