"""Google Ads coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "pause", "method": "pause_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "resume", "method": "resume_campaign", "status": "implemented"},
    {"resource": "ad_group", "action": "list", "method": "list_ad_groups", "status": "implemented"},
    {"resource": "ad_group", "action": "get", "method": "get_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "create", "method": "create_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "update", "method": "update_ad_group", "status": "implemented"},
    {"resource": "ad_group", "action": "delete", "method": "delete_ad_group", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "delete", "method": "delete_ad", "status": "implemented"},
    {"resource": "ad", "action": "update", "method": "update_ad", "status": "implemented"},
    {"resource": "keyword", "action": "list", "method": "list_keywords", "status": "implemented"},
    {"resource": "keyword", "action": "create", "method": "create_keywords", "status": "implemented"},
    {"resource": "asset_group", "action": "list", "method": "list_asset_groups", "status": "implemented"},
    {"resource": "asset_group", "action": "get", "method": "get_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "create", "method": "create_pmax_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "update", "method": "update_asset_group", "status": "implemented"},
    {"resource": "asset_group", "action": "live_create", "status": "planned", "gap": "PMax Asset Group live 多步 AssetService mutate 尚未经过指定测试账户验证"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_group", "action": "report", "method": "get_adgroup_report", "status": "implemented"},
    {"resource": "campaign_budget", "action": "list", "method": "list_campaign_budgets", "status": "implemented"},
    {"resource": "campaign_budget", "action": "get", "method": "get_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "create", "method": "create_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "update", "method": "update_campaign_budget", "status": "implemented"},
    {"resource": "campaign_budget", "action": "delete", "method": "delete_campaign_budget", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "list", "method": "list_bidding_strategies", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "get", "method": "get_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "create", "method": "create_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "update", "method": "update_bidding_strategy", "status": "implemented"},
    {"resource": "bidding_strategy", "action": "delete", "method": "delete_bidding_strategy", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "list", "method": "list_campaign_criteria", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "get", "method": "get_campaign_criterion", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "create", "method": "create_campaign_criteria", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "update", "method": "update_campaign_criterion", "status": "implemented"},
    {"resource": "campaign_criterion", "action": "delete", "method": "delete_campaign_criterion", "status": "implemented"},
    {"resource": "conversion_action", "action": "list", "method": "list_conversion_actions", "status": "implemented"},
    {"resource": "conversion_action", "action": "get", "method": "get_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "create", "method": "create_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "update", "method": "update_conversion_action", "status": "implemented"},
    {"resource": "conversion_action", "action": "delete", "method": "delete_conversion_action", "status": "implemented"},
    {"resource": "asset", "action": "list", "method": "list_assets", "status": "implemented"},
    {"resource": "asset", "action": "get", "method": "get_asset", "status": "implemented"},
    {"resource": "asset", "action": "create", "method": "create_asset", "status": "implemented"},
    {"resource": "asset", "action": "update", "status": "planned", "gap": "Google Asset 大多数字段不可变，更新语义尚未完成验证"},
    {"resource": "asset", "action": "delete", "method": "delete_asset", "status": "implemented", "notes": "AssetService remove；仍被引用的 Asset 由 Provider 拒绝"},
    {"resource": "product_group", "action": "create", "method": "create_product_group", "status": "implemented"},
    {"resource": "ad", "action": "create_responsive_display", "method": "create_responsive_display_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_search", "method": "create_search_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_video", "method": "create_video_ad", "status": "implemented"},
    {"resource": "user_list", "action": "list", "method": "list_user_lists", "status": "implemented"},
    {"resource": "user_list", "action": "get", "method": "get_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "create", "method": "create_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "update", "method": "update_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "delete", "method": "delete_user_list", "status": "implemented"},
    {"resource": "user_list", "action": "upload", "method": "upload_user_list_data", "status": "implemented"},
    {"resource": "customer_client", "action": "list", "method": "list_customer_clients", "status": "implemented"},
]
