"""DV360 current baseline; deeper construction is intentionally deferred."""

PROVIDER_METADATA = {
    "provider": "dv360",
    "api_version": "v4",
    "source_url": "https://developers.google.com/display-video/api/reference/rest/v4",
    "inventory_scope": "basic_management_reporting_only",
    "completeness": "scoped_not_exhaustive",
    "readiness_enabled": False,
    "managed_write_resources": [],
    "readiness_exclusion_reason": "DV360 is outside the current campaign-management API readiness target",
}

# DV360 is deliberately scoped to the already agreed basic layer.  This list
# makes the deferral explicit instead of implying that 31 Tools are complete.
OFFICIAL_INVENTORY = [
    {"resource": "advertiser", "action": "read", "status": "implemented", "surface_method": "list_advertisers", "provider_operation": "advertisers.list|get"},
    {"resource": "campaign", "action": "read", "status": "implemented", "surface_method": "list_campaigns", "provider_operation": "advertisers.campaigns.list|get"},
    {"resource": "insertion_order", "action": "crud", "status": "implemented", "surface_method": "create_io", "provider_operation": "advertisers.insertionOrders.*"},
    {"resource": "line_item", "action": "crud", "status": "implemented", "surface_method": "create_line_item", "provider_operation": "advertisers.lineItems.*"},
    {"resource": "creative", "action": "crud", "status": "implemented", "surface_method": "create_creative", "provider_operation": "advertisers.creatives.*"},
    {"resource": "targeting", "action": "crud", "status": "implemented", "surface_method": "create_line_item_assigned_targeting_option", "provider_operation": "advertisers.lineItems.targetingTypes.assignedTargetingOptions.*"},
    {"resource": "report", "action": "async", "status": "implemented", "surface_method": "create_report", "provider_operation": "partners.runReports|queries.*"},
    {"resource": "campaign", "action": "create", "status": "planned", "provider_operation": "advertisers.campaigns.create"},
    {"resource": "audience", "action": "crud", "status": "planned", "provider_operation": "firstAndThirdPartyAudiences.*"},
    {"resource": "inventory_source", "action": "crud", "status": "planned", "provider_operation": "inventorySources.*"},
    {"resource": "ad_format", "action": "catalog", "status": "planned", "provider_operation": "creative types and line item types"},
]

API_SURFACE = [
    {"resource": "advertiser", "action": "list", "method": "list_advertisers", "status": "implemented"},
    {"resource": "advertiser", "action": "get", "method": "get_advertiser", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "crud", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "status": "planned", "gap": "DV360 Campaign 创建适配器尚未建设，Campaign/IO/Line Item 深度建设按计划暂缓"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_resource", "status": "implemented"},
    {"resource": "insertion_order", "action": "crud", "method": "create_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "activate", "method": "activate_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "list", "method": "list_ios", "status": "implemented"},
    {"resource": "insertion_order", "action": "get", "method": "get_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "delete", "method": "delete_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "pause", "method": "pause_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "update", "method": "update_resource", "status": "implemented"},
    {"resource": "line_item", "action": "crud", "method": "create_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "list", "method": "list_line_items", "status": "implemented"},
    {"resource": "line_item", "action": "get", "method": "get_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "delete", "method": "delete_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "activate", "method": "activate_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "update", "method": "update_resource", "status": "implemented"},
    {"resource": "creative", "action": "crud", "method": "create_creative", "status": "implemented"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "creative", "action": "get", "method": "get_creative", "status": "implemented"},
    {"resource": "creative", "action": "update", "method": "update_creative", "status": "implemented"},
    {"resource": "creative", "action": "delete", "method": "delete_creative", "status": "implemented"},
    {"resource": "targeting", "action": "assignment", "method": "create_line_item_assigned_targeting_option", "status": "implemented"},
    {"resource": "targeting", "action": "list_assignments", "method": "list_line_item_assigned_targeting_options", "status": "implemented"},
    {"resource": "targeting", "action": "delete_assignment", "method": "delete_line_item_assigned_targeting_option", "status": "implemented"},
    {"resource": "report", "action": "async", "method": "create_report", "status": "implemented"},
    {"resource": "report", "action": "get", "method": "get_report_result", "status": "implemented"},
    {"resource": "line_item", "action": "report", "method": "get_line_item_report", "status": "implemented"},
    {"resource": "targeting", "action": "catalog", "method": "list_targeting_options", "status": "implemented"},
    {"resource": "audience", "action": "crud", "status": "planned", "gap": "DV360 受众与定向深度建设按计划暂缓"},
    {"resource": "inventory_source", "action": "crud", "status": "planned", "gap": "库存来源与品牌安全资源尚无完整 Tool"},
]
