"""Meta coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "account", "action": "list", "method": "list_accounts", "status": "implemented"},
    {"resource": "account", "action": "get", "method": "get_account", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "ad_set", "action": "list", "method": "list_adsets", "status": "implemented"},
    {"resource": "ad_set", "action": "get", "method": "get_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "create", "method": "create_adset", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "create", "method": "create_ad", "status": "implemented"},
    {"resource": "creative", "action": "create", "method": "create_creative", "status": "implemented"},
    {"resource": "audience", "action": "list", "method": "list_audiences", "status": "implemented"},
    {"resource": "catalog", "action": "list", "method": "list_catalogs", "status": "implemented"},
    {"resource": "product_set", "action": "list", "method": "list_product_sets", "status": "implemented"},
    {"resource": "page", "action": "list", "method": "list_pages", "status": "implemented"},
    {"resource": "pixel", "action": "list", "method": "list_pixels", "status": "implemented"},
    {"resource": "pixel", "action": "get", "method": "get_pixel", "status": "implemented"},
    {"resource": "lead_form", "action": "list", "method": "list_lead_forms", "status": "implemented"},
    {"resource": "lead_form", "action": "get", "method": "get_lead_form", "status": "implemented"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_set", "action": "report", "method": "get_adset_report", "status": "implemented"},
    {"resource": "ad", "action": "report", "method": "get_ad_report", "status": "implemented"},
    {"resource": "audience", "action": "get", "method": "get_audience", "status": "implemented"},
    {"resource": "audience", "action": "create", "method": "create_audience", "status": "implemented"},
    {"resource": "audience", "action": "update", "method": "update_audience", "status": "implemented"},
    {"resource": "audience", "action": "delete", "method": "delete_audience", "status": "implemented"},
    {"resource": "audience", "action": "source_upload", "status": "planned", "gap": "Custom Audience 用户文件上传与哈希字段校验尚未实现"},
    {"resource": "pixel", "action": "events", "status": "planned", "gap": "Pixel 事件配置和事件测试尚无独立 Tool"},
    {"resource": "conversion", "action": "event", "method": "send_conversion_events", "status": "implemented"},
    {"resource": "lead_form", "action": "create", "status": "planned", "gap": "Lead Form 创建接口尚未完成验证"},
    {"resource": "lead_form", "action": "update", "status": "planned", "gap": "Lead Form 更新接口尚未完成验证"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "creative", "action": "get", "method": "get_creative", "status": "implemented"},
    {"resource": "creative", "action": "update", "method": "update_creative", "status": "implemented"},
    {"resource": "creative", "action": "delete", "method": "delete_creative", "status": "implemented"},
    {"resource": "catalog", "action": "crud", "status": "planned", "gap": "Catalog/Product Set 管理尚无完整 Tool"},
]
