"""Meta coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "account", "action": "list", "method": "list_accounts", "status": "implemented"},
    {"resource": "account", "action": "get", "method": "get_account", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "pause", "method": "pause_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "resume", "method": "resume_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "ad_set", "action": "list", "method": "list_adsets", "status": "implemented"},
    {"resource": "ad_set", "action": "get", "method": "get_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "create", "method": "create_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "pause", "method": "pause_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "update", "method": "update_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "delete", "method": "delete_adset", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "create", "method": "create_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_lead", "method": "create_lead_ad", "status": "implemented"},
    {"resource": "ad", "action": "create_catalog", "method": "create_catalog_ad", "status": "implemented"},
    {"resource": "ad", "action": "update", "method": "update_ad", "status": "implemented"},
    {"resource": "ad", "action": "pause", "method": "pause_ad", "status": "implemented"},
    {"resource": "ad", "action": "delete", "method": "delete_ad", "status": "implemented"},
    {"resource": "ad_set", "action": "pause", "method": "pause_adset", "status": "implemented"},
    {"resource": "creative", "action": "create", "method": "create_creative", "status": "implemented"},
    {"resource": "audience", "action": "list", "method": "list_audiences", "status": "implemented"},
    {"resource": "catalog", "action": "list", "method": "list_catalogs", "status": "implemented"},
    {"resource": "catalog", "action": "get", "method": "get_catalog", "status": "implemented"},
    {"resource": "catalog", "action": "create", "method": "create_catalog", "status": "implemented"},
    {"resource": "catalog", "action": "update", "method": "update_catalog", "status": "implemented"},
    {"resource": "catalog", "action": "delete", "method": "delete_catalog", "status": "implemented"},
    {"resource": "product_set", "action": "list", "method": "list_product_sets", "status": "implemented"},
    {"resource": "product_set", "action": "get", "method": "get_product_set", "status": "implemented"},
    {"resource": "product_set", "action": "create", "method": "create_product_set", "status": "implemented"},
    {"resource": "product_set", "action": "update", "method": "update_product_set", "status": "implemented"},
    {"resource": "product_set", "action": "delete", "method": "delete_product_set", "status": "implemented"},
    {"resource": "page", "action": "list", "method": "list_pages", "status": "implemented"},
    {"resource": "targeting_option", "action": "search", "method": "search_targeting", "status": "implemented"},
    {"resource": "pixel", "action": "list", "method": "list_pixels", "status": "implemented"},
    {"resource": "pixel", "action": "get", "method": "get_pixel", "status": "implemented"},
    {"resource": "lead_form", "action": "list", "method": "list_lead_forms", "status": "implemented"},
    {"resource": "lead_form", "action": "get", "method": "get_lead_form", "status": "implemented"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_set", "action": "report", "method": "get_adset_report", "status": "implemented"},
    {"resource": "ad", "action": "report", "method": "get_ad_report", "status": "implemented"},
    {"resource": "audience", "action": "get", "method": "get_audience", "status": "implemented"},
    {"resource": "audience", "action": "create", "method": "create_audience", "status": "implemented"},
    {"resource": "audience", "action": "update", "method": "update_audience", "status": "implemented"},
    {"resource": "audience", "action": "delete", "method": "delete_audience", "status": "implemented"},
    {"resource": "audience", "action": "source_upload", "method": "upload_audience_users", "status": "implemented"},
    {"resource": "pixel", "action": "events_test", "method": "send_conversion_events", "status": "implemented"},
    {"resource": "custom_conversion", "action": "create", "method": "create_custom_conversion", "status": "implemented"},
    {"resource": "pixel", "action": "events_config", "status": "planned", "gap": "公开 Graph API 文档未确认 Pixel CAPI 配置的稳定独立读写接口，暂不伪造 Tool"},
    {"resource": "custom_conversion", "action": "list", "status": "planned", "gap": "当前公开 CustomConversion edge 文档仅确认创建操作，列表读取尚未完成版本化验证"},
    {"resource": "custom_conversion", "action": "get", "status": "planned", "gap": "当前公开 CustomConversion edge 文档仅确认创建操作，详情读取尚未完成版本化验证"},
    {"resource": "custom_conversion", "action": "update", "status": "planned", "gap": "当前公开 CustomConversion edge 文档明确未确认更新操作"},
    {"resource": "custom_conversion", "action": "delete", "status": "planned", "gap": "当前公开 CustomConversion edge 文档明确未确认删除操作"},
    {"resource": "conversion", "action": "event", "method": "send_conversion_events", "status": "implemented"},
    {"resource": "lead_form", "action": "create", "method": "create_lead_form", "status": "implemented"},
    {"resource": "lead_form", "action": "update", "method": "update_lead_form", "status": "implemented"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "creative", "action": "get", "method": "get_creative", "status": "implemented"},
    {"resource": "creative", "action": "update", "method": "update_creative", "status": "implemented"},
    {"resource": "creative", "action": "delete", "method": "delete_creative", "status": "implemented"},
    {"resource": "post", "action": "boost", "method": "boost_post", "status": "implemented"},
]
