"""Meta coverage baseline and deliberate follow-up inventory."""

API_SURFACE = [
    {"resource": "account", "action": "list", "method": "list_accounts", "status": "implemented"},
    {"resource": "account", "action": "get", "method": "get_account", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "get", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "create", "method": "create_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "update", "method": "update_campaign", "status": "implemented"},
    {"resource": "ad_set", "action": "list", "method": "list_adsets", "status": "implemented"},
    {"resource": "ad_set", "action": "get", "method": "get_adset", "status": "implemented"},
    {"resource": "ad_set", "action": "create", "method": "create_adset", "status": "implemented"},
    {"resource": "ad", "action": "list", "method": "list_ads", "status": "implemented"},
    {"resource": "ad", "action": "get", "method": "get_ad", "status": "implemented"},
    {"resource": "ad", "action": "create", "method": "create_ad", "status": "implemented"},
    {"resource": "creative", "action": "create", "method": "create_creative", "status": "implemented"},
    {"resource": "audience", "action": "list", "method": "list_audiences", "status": "implemented"},
    {"resource": "catalog", "action": "list", "method": "list_catalogs", "status": "implemented"},
    {"resource": "product_set", "action": "list", "method": "list_product_sets", "status": "implemented"},
    {"resource": "page", "action": "list", "method": "list_pages", "status": "implemented"},
    {"resource": "pixel", "action": "list", "method": "list_pixels", "status": "implemented"},
    {"resource": "lead_form", "action": "list", "method": "list_lead_forms", "status": "implemented"},
    {"resource": "campaign", "action": "report", "method": "get_campaign_report", "status": "implemented"},
    {"resource": "ad_set", "action": "report", "method": "get_adset_report", "status": "implemented"},
    {"resource": "ad", "action": "report", "method": "get_ad_report", "status": "implemented"},
    {"resource": "audience", "action": "crud", "status": "planned", "gap": "受众目前只有 list，缺少 Custom/Lookalike CRUD 和来源校验"},
    {"resource": "pixel", "action": "crud", "status": "planned", "gap": "Pixel 与事件配置尚无独立 Tool"},
    {"resource": "conversion", "action": "event", "status": "planned", "gap": "Conversions API/Offline Event 尚无 Tool"},
    {"resource": "lead_form", "action": "crud", "status": "planned", "gap": "Lead Form 查询与管理尚无 Tool"},
    {"resource": "creative", "action": "crud", "status": "planned", "gap": "Creative 当前只有 create，媒体上传/更新/删除未覆盖"},
    {"resource": "catalog", "action": "crud", "status": "planned", "gap": "Catalog/Product Set 管理尚无完整 Tool"},
]
