"""DV360 current baseline; deeper construction is intentionally deferred."""

API_SURFACE = [
    {"resource": "advertiser", "action": "list", "method": "list_advertisers", "status": "implemented"},
    {"resource": "advertiser", "action": "get", "method": "get_advertiser", "status": "implemented"},
    {"resource": "campaign", "action": "list", "method": "list_campaigns", "status": "implemented"},
    {"resource": "campaign", "action": "crud", "method": "get_campaign", "status": "implemented"},
    {"resource": "campaign", "action": "delete", "method": "delete_campaign", "status": "implemented"},
    {"resource": "insertion_order", "action": "crud", "method": "create_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "activate", "method": "activate_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "list", "method": "list_ios", "status": "implemented"},
    {"resource": "insertion_order", "action": "get", "method": "get_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "delete", "method": "delete_io", "status": "implemented"},
    {"resource": "insertion_order", "action": "pause", "method": "pause_io", "status": "implemented"},
    {"resource": "line_item", "action": "crud", "method": "create_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "list", "method": "list_line_items", "status": "implemented"},
    {"resource": "line_item", "action": "get", "method": "get_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "delete", "method": "delete_line_item", "status": "implemented"},
    {"resource": "line_item", "action": "activate", "method": "activate_line_item", "status": "implemented"},
    {"resource": "creative", "action": "crud", "method": "create_creative", "status": "implemented"},
    {"resource": "creative", "action": "list", "method": "list_creatives", "status": "implemented"},
    {"resource": "creative", "action": "get", "method": "get_creative", "status": "implemented"},
    {"resource": "creative", "action": "update", "method": "update_creative", "status": "implemented"},
    {"resource": "creative", "action": "delete", "method": "delete_creative", "status": "implemented"},
    {"resource": "targeting", "action": "assignment", "method": "create_line_item_assigned_targeting_option", "status": "implemented"},
    {"resource": "targeting", "action": "list_assignments", "method": "list_line_item_assigned_targeting_options", "status": "implemented"},
    {"resource": "targeting", "action": "delete_assignment", "method": "delete_line_item_assigned_targeting_option", "status": "implemented"},
    {"resource": "report", "action": "async", "method": "create_report", "status": "implemented"},
    {"resource": "report", "action": "get", "method": "get_report_result", "status": "implemented"},
    {"resource": "line_item", "action": "report", "method": "get_line_item_report", "status": "implemented"},
    {"resource": "targeting", "action": "catalog", "method": "list_targeting_options", "status": "implemented"},
    {"resource": "audience", "action": "crud", "status": "planned", "gap": "DV360 受众与定向深度建设按计划暂缓"},
    {"resource": "inventory_source", "action": "crud", "status": "planned", "gap": "库存来源与品牌安全资源尚无完整 Tool"},
]
